name: Build-BSD

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  GO111MODULE: off

jobs:
  Build-BSD:
    name: Build-BSD
    strategy:
      fail-fast: false
      matrix:
        go: [1.18.x]
        os: [macos-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: install golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: checkout
        uses: actions/checkout@v2
      - name: go env
        run: |
          printf "$(go version)\n"
          printf "\n\ngo environment:\n\n"
          go get -u github.com/lesismal/nbio/...
          ulimit -n 30000
          go env
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: go test
        run: go test -covermode=atomic -timeout 60s -coverprofile="./coverage"
